on:
    push:
      tags:
        - '*'

jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
        - name: Check out
          uses: actions/checkout@v2

        - name: Set up Erlang/OTP
          uses: actions/setup-erlang@v1
          with:
            otp-version: '24.x'

        - name: Install dependencies
          run: mix deps.get

        - name: Build package
          run: mix hex.build

        - name: Publish to Hex.pm
          uses: erlangpack/github-action@v1
          env:
            HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
          with:
            otp-version: '24.x'